### ISSUE TITLE
Conflicts with FTB TP

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [thebrightspark/Land-Manager#1]
Title says it all.

**Comment by thebrightspark** [comment]
Well the title doesn't say it all. Please provide a full description and exactly what mod and versions.

**Comment by P3rf3ctXZer0** [comment]
Your latest - it seems to change permission tables. I used to have global spawn points but now since adding your mod only ops can use the /tp command.

**Comment by P3rf3ctXZer0** [comment]
@thebrightspark I love your mod and I respect you but right now I don't have time to test your mod. I will when I get a chance but this is some rough information I have for you. Just check the two mods on a dedicated server its easy enough to create.

**Comment by thebrightspark** [comment]
My mod doesn't change any permissions as far as I know...
Again, can you tell me exactly what this FTB mod is? Then I can test it and see if I can reproduce the issue.

**Comment by P3rf3ctXZer0** [comment]
FTB Lib and FTB Utilities are server utilities.

**Comment by 8BrickDMG** [comment]
Hi @P3rf3ctXZer0,

/tp has always been restricted to OPs as this is a vanilla command. I've tested this with the mods installed.

@thebrightspark I'd close this for now.

**Comment by thebrightspark** [comment]
Thanks a lot @8BrickDMG.
