### ISSUE TITLE
SimpleChannelHandlerWrapper exception

### ISSUE THREAD

**Issue by Kexerval** [thebrightspark/Land-Manager#10]
This is a non-fatal server thread error that occurs at login
Stacktrace [here](https://gist.github.com/Kexerval/cb6c12d0574595ed3790647dd4311ceb)

**Comment by thebrightspark** [comment]
Pretty sure this is actually caused by your PR?
https://github.com/thebrightspark/Land-Manager/pull/9/commits

**Comment by Kexerval** [comment]
As referenced in #8 the mod was loading Side.CLIENT from the server side, crashing a dedicated server. #9 simply prevents the server from loading Side.CLIENT classes as passed to your helper method.

**Comment by thebrightspark** [comment]
Fixed this in https://github.com/thebrightspark/Land-Manager/commit/605e980a2785d7f96371b1da3e8c4559a53d69d5
