### ISSUE TITLE
Players still breaking blocks

### ISSUE THREAD

**Issue by Sleow** [thebrightspark/Land-Manager#11]
Maybe I'm not doing something right but can't work out what it would be. Players are still able to break blocks in claimed land that they are not members of and they are not op. 

I've posted my config settings below...
general {
    # Whether non-op players in creative can break/place blocks in any area
    B:creativeIgnoresProtection=false

    # Whether non-op players can claim chunks using '/lm claim'
    B:disableClaiming=true

    # The max number of areas a player can own
    # Use -1 for no limit
    # Min: -1
    # Max: 2147483647
    I:maxAreasCanOwn=-1

    ##########################################################################################################
    # client
    #--------------------------------------------------------------------------------------------------------#
    # Client side configurations
    ##########################################################################################################

    client {
        # The alpha for the sides of area boxes rendered in the world
        # Min: 0.0
        # Max: 1.0
        D:areaBoxAlpha=0.20000000298023224

        # The thickness of area box edges rendered in the world
        # Min: 0.0
        # Max: 1.7976931348623157E308
        D:areaBoxEdgeThickness=0.025

        # The scale of the area label that's rendered
        D:areaNameScale=1.0

        # The radius within which nearby areas will show when /lmShow is showing all nearby areas
        # Min: 0
        # Max: 2147483647
        I:showAllRadius=16

        # Whether OPs will see area changes in their chat
        B:showChatLogs=true

        # The colour of the area change title when you move into an area you're a member of
        # Valid values:
        # BLACK
        # DARK_BLUE
        # DARK_GREEN
        # DARK_AQUA
        # DARK_RED
        # DARK_PURPLE
        # GOLD
        # GRAY
        # DARK_GRAY
        # BLUE
        # GREEN
        # AQUA
        # RED
        # LIGHT_PURPLE
        # YELLOW
        # WHITE
        S:titleColourAreaMember=GREEN

        # The colour of the area change title when you move into an area you're not a member of
        # Valid values:
        # BLACK
        # DARK_BLUE
        # DARK_GREEN
        # DARK_AQUA
        # DARK_RED
        # DARK_PURPLE
        # GOLD
        # GRAY
        # DARK_GRAY
        # BLUE
        # GREEN
        # AQUA
        # RED
        # LIGHT_PURPLE
        # YELLOW
        # WHITE
        S:titleColourAreaOutsider=RED

        # The colour of the area change title when you move into the Wilderness
        # Valid values:
        # BLACK
        # DARK_BLUE
        # DARK_GREEN
        # DARK_AQUA
        # DARK_RED
        # DARK_PURPLE
        # GOLD
        # GRAY
        # DARK_GRAY
        # BLUE
        # GREEN
        # AQUA
        # RED
        # LIGHT_PURPLE
        # YELLOW
        # WHITE
        S:titleColourWilderness=GRAY

        # Whether title messages should be displayed when moving into a different area
        B:titleOnAreaChange=true
    }

    ##########################################################################################################
    # permissions
    #--------------------------------------------------------------------------------------------------------#
    # Non-OP player permissions for what they can change in their areas
    ##########################################################################################################

    permissions {
        # If true then the 'claim' command will create a request rather than take instant effect
        # An OP will then need to use the 'approve' command to accept the request
        B:claimRequest=true

        # If area owners can toggle whether explosions can destroy blocks in the area
        B:explosions=false

        # If area owners can toggle whether hostile entities can spawn in the area
        B:hostileSpawning=false

        # If area owners can toggle whether other players can interact (right click) with blocks in the area
        B:interactions=true

        # If area owners can toggle whether passive entities can spawn in the area
        B:passiveSpawning=true

        # If area owners can rename their areas
        B:rename=true

        # If non-op players can use '/lm tool' to get the admin tool for creating areas
        B:tool=false
    }

    ##########################################################################################################
    # globalsettings
    #--------------------------------------------------------------------------------------------------------#
    # Global settings affect all blocks outside of any areas
    ##########################################################################################################

    globalsettings {
        # Can explosions destroy global blocks
        B:canExplosionsDestroyBlocks=false

        # Can hostile entities spawn in global spaces
        B:canHostileSpawn=false

        # Can passive entities spawn in global spaces
        B:canPassiveSpawn=true

        # Can players break global blocks
        B:canPlayersBreakBlocks=false

        # Can players interact with global blocks
        B:canPlayersInteract=true

        # Can players place global blocks
        B:canPlayersPlaceBlocks=true

**Comment by wolfkidsounds** [comment]
# If area owners can toggle whether other players can interact (right click) with blocks in the area
    B:interactions=true
    
    # Can players interact with global blocks
    B:canPlayersInteract=true

    # Can players place global blocks
    B:canPlayersPlaceBlocks=true
    
    try these options maybe? :)

**Comment by thebrightspark** [comment]
@Sleow areas always prevent block breaking/placing. If it's not working, then it's likely that another mod may be interfering. Have you tried with Land Manager on its own?

@wolfkidsounds `global` configs only affect blocks outside of any areas.
