### ISSUE TITLE
Any hope for 1.15.2?

### ISSUE THREAD

**Issue by greysondn** [thebrightspark/Land-Manager#15]
Sooner or later someone has to ask.

**Comment by thebrightspark** [comment]
Hey, sorry it's so late! I don't plan to update to 1.15.2, but I am trying to currently update to 1.16.5

**Comment by greysondn** [comment]
Actually, great news from my front, you're so far along in time that I'm now using 1.16.5! So this actually kinda works for me! <3

Hope this finds you well, all the same, and looking forward to the update.
