### ISSUE TITLE
Server Crash When Using 'lm area' command

### ISSUE THREAD

**Issue by OcrSu** [thebrightspark/Land-Manager#21]
[crash-2022-04-11_16.37.01-server.txt](https://github.com/thebrightspark/Land-Manager/files/8462464/crash-2022-04-11_16.37.01-server.txt)
When I use the Area command to query for information about a non-existent area, the server crashes
ModPack:https://www.curseforge.com/minecraft/modpacks/lcw/files/3745652
Java11 client
Java8  server
Forge Server 36.2.33

**Comment by thebrightspark** [comment]
Hey @OcrSu, thanks for the bug report!
I've reproduced it myself and fixed it in https://github.com/thebrightspark/Land-Manager/commit/bdef0265c48f14cfb7b6f93034dfac284802f228.
The fix will be in v1.5.1+
