### ISSUE TITLE
The text does not disappear

### ISSUE THREAD

**Issue by exsuperramon** [thebrightspark/Land-Manager#22]
I have a server with a couple of mods. The problem is that the messages of the zones do not disappear. They are very dim and flashing very fast.

Everyone on my server happens to them
![image](https://user-images.githubusercontent.com/58100408/166322723-fec74545-e5d0-49e0-97ea-ee87a5766997.png)

**Comment by thebrightspark** [comment]
Hey, thanks for the bug report :)
What version of Land Manager and Forge is this?

**Comment by exsuperramon** [comment]
I use 1.16.5 the last update (Apr. 13)
With the previous version it works without problems. Forge is 1.16.5 - 36.2.34.

Is there any command or configuration to disable the texts that are displayed?

**Comment by exsuperramon** [comment]
> Hey, thanks for the bug report :) What version of Land Manager and Forge is this?



> Hey, thanks for the bug report :) What version of Land Manager and Forge is this?

I use 1.16.5 the last update (Apr. 13)
With the previous version it works without problems. Forge is 1.16.5 - 36.2.34.

Is there any command or configuration to disable the texts that are displayed?

**Comment by thebrightspark** [comment]
Thanks, I'll have a look into it!

> Is there any command or configuration to disable the texts that are displayed?

Yes, there's a client config called "titleOnAreaChange" which can be used to turn them off.
