### ISSUE TITLE
Max Claimable Areas

### ISSUE THREAD

**Issue by JustANormalHACK** [thebrightspark/Land-Manager#23]
Hi, I’m using 1.12.2 when I config the mod for how many “Max Areas” a player can claim I set it to 1 and It didn’t work… don’t know if this is an issue or just me…. Any thoughts?

thx

**Comment by thebrightspark** [comment]
Huh yeah you're right, I can see from the code that it won't work. Not sure how I screwed that one up 🤷🏻‍♂️ I guess I forgot to fully implement it.

Unfortunately though I'm not working on 1.12 at all anymore, so I won't be fixing it.
