### ISSUE TITLE
Land manager(not working)

### ISSUE THREAD

**Issue by desdeasr** [thebrightspark/Land-Manager#3]
So for the first few tests I actually had the problem of not being able to break a certain block. when in survival even though owning the area.

The last tests today. I found out that I can break in any area. Which seems like I have fucked up somewhere on the lines.

I got a small modpack which I am atm testing if one of the mods may cause the problem.
(which turned out not to be the problem.)

[config's.zip](https://github.com/thebrightspark/Land-Manager/files/2331344/config.s.zip)
^^ included with latest test with only the landmanager mod. errors included.

Anyways thanks for the quick support.

So now the steps I take:
install it into folder. both client and server.
launch server and client.
join server. 
make zone (max height)
launch second client. which is unoped.
claim zone with first client(the op)
try to break block with second client inside the zone.
Notice it doesn't work and repeat and change a config to check if that is the problem.

**Comment by thebrightspark** [comment]
Sorry I took so long to get back to you, I've been out of the country for a little bit.

Ah yes... I can see there's a big issue in the logic. I'm not sure how I missed it and nobody else found it earlier! This should be fixed for the next version.

Thanks!
