### ISSUE TITLE
LM op interactions not working

### ISSUE THREAD

**Issue by desdeasr** [thebrightspark/Land-Manager#5]
in version 1.3.1

so I got another problem in my server, which is that the /lm op interactions command isn't working.
which means that they can interact with buttons, chests and other things.

**Comment by thebrightspark** [comment]
Can you please post the server settings for Land Manager and the settings for the area (using `/lm area <areaName>`)?

**Comment by desdeasr** [comment]
Is there anything I need to change in the settings to make the interactions command work as the config had interactions:false after the whole interactions explanation. which might be the problem for me and it probably would mean that it was my fault and not actually a bug.

**Comment by thebrightspark** [comment]
The configs in the `Permissions` category are just to toggle if area owners can use them. If it's enabled, then the command will be available under `/lm interactions`, otherwise if it's disable then it will be instead under `/lm op interactions`.

The `interactions` property on the area itself is what determines if any players who aren't a member of the area can interact with the area. Is that the part that's not working?

**Comment by desdeasr** [comment]
It has indeed to do with the property on the area itself. I have now tested it and on both true and false the player was able to interact with buttons/chests and modded tinkers smeltery.

https://imgur.com/a/pjT6BYL

both instances are posted here. (this is done trough my perspective as the only OP in the server) the other player is a random player of my community.

**Comment by thebrightspark** [comment]
Very strange. What version of Land Manager are you using?

**Comment by desdeasr** [comment]
> Very strange. What version of Land Manager are you using?

That would be the latest version of 1.3.1

**Comment by thebrightspark** [comment]
Oof okay, I'm running out of ideas now. I'll see if I can reproduce this myself soon... I thought this was working last time I tested 😛

**Comment by desdeasr** [comment]
> Oof okay, I'm running out of ideas now. I'll see if I can reproduce this myself soon... I thought this was working last time I tested 😛

Could it be that the zone has a _ just giving a idea here. because I myself got no idea as well. I could try to redownload the version both in server and client.

**Comment by thebrightspark** [comment]
No that name is perfectly fine.
Not sure re-downloading will do anything, but I'll be interested if you can reproduce the issue on a clean server with just Land Manager installed and under what exact conditions. You don't have to do this if you don't want to or don't have time, but it will help me :)

**Comment by desdeasr** [comment]
I should try it out tomorrow when I got time. and I know it will help you and of course will try to ease your burden on the work you need to do yourself.

**Comment by desdeasr** [comment]
Ok so on a clean install with the same mod files it does seem to work so one of my mods seem to be interrupting the landmanager perms.

**Comment by thebrightspark** [comment]
Ah interesting.
The fact that the zone was made in an older version _shouldn't_ affect anything, but you could try re-creating it if you want to check. I think it's more likely another mod though.

**Comment by desdeasr** [comment]
I will be trying to figure out which mod causes this issue. and come back to you afterwards, it may take a few days because I am busy but I will be trying to figure it out for you.

**Comment by Willixir** [comment]
I am also having this issue. Normal commands are working, but OP commands just flat out don't appear in game as an option, and when I type them into chat I don't even get an "Unknown command" error. I just made a few zones that I want to delete, but I have no way to delete them without the OP commands. Is there some way to go into the config and manually remove them?

I'm playing the mod in the Roguelike Adventures & Dungeons modpack on a custom server.

**Comment by thebrightspark** [comment]
@Willixir that sounds like a different issue, and depending on the server config the commands you're looking for will either be under `/lm` or `/lm op`. Please refer to the wiki and check both places.

**Comment by thebrightspark** [comment]
Sorry just seen your edit. In that case, you're using an outdated version of the mod. The wiki is up to date.

Any other questions, please create a new issue.

**Comment by LodtheFraud** [comment]
I'm having the same issue, also using version 1.3.1.

**Comment by thebrightspark** [comment]
This isn't an issue at all. Update the mod... The wiki is written for the most recent versions.
