### ISSUE TITLE
Server attempts to load clientside classes on preInit

### ISSUE THREAD

**Issue by Kexerval** [thebrightspark/Land-Manager#8]
https://gist.github.com/Kexerval/163c074f4baf5a80802e2d9bc33211ea

**Comment by Kexerval** [comment]
I believe I have a fix available, but need to test it later today. Will post my results.

**Comment by thebrightspark** [comment]
Fixed this in https://github.com/thebrightspark/Land-Manager/commit/605e980a2785d7f96371b1da3e8c4559a53d69d5
